### ISSUE TITLE
Not able to create access token using the application

### ISSUE THREAD

**Issue by dvojtise** [doris-ffessm/doris-android#206]
in the current version the access_token creation doesn't finish completly

the command : `./gradlew clean buildDorisDB -Pargs='-u dvojtise@gmail.com -i -noFetch'`
 fails when it comes to use the authorization code to get the access_token

```
2024-12-28 09:15:45.561:INFO::Logging to STDERR via org.mortbay.log.StdErrLog
2024-12-28 09:15:45.562:INFO::jetty-6.1.26
2024-12-28 09:15:45.577:INFO::Started SocketConnector@localhost:8087
Please open the following address in your browser:
  https://doris.ffessm.fr/oauth/authorize?client_id=XXXXXXXX&redirect_uri=http://localhost:8087/Callback&response_type=code
Attempting to open that address in the default browser now...
Opening in existing browser session.
2024-12-28 09:15:47.903:INFO::Stopped SocketConnector@localhost:8087
24-12-28 09:15:47 ERROR - Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: com.google.api.client.http.javanet.NetHttpResponse$SizeValidatingInputStream@5d0a1059; line: 1, column: 2] - at fr.ffessm.doris.prefetch.PrefetchDorisWebSite.main(PrefetchDorisWebSite.java:125)
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: com.google.api.client.http.javanet.NetHttpResponse$SizeValidatingInputStream@5d0a1059; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1378)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:599)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:520)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2275)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:788)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:674)
        at com.google.api.client.json.jackson2.JacksonParser.nextToken(JacksonParser.java:55)
        at com.google.api.client.json.JsonParser.startParsing(JsonParser.java:220)
        at com.google.api.client.json.JsonParser.parse(JsonParser.java:379)
        at com.google.api.client.json.JsonParser.parse(JsonParser.java:354)
        at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:87)
        at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:81)
        at com.google.api.client.http.HttpResponse.parseAs(HttpResponse.java:459)
        at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307)
        at com.google.api.client.extensions.java6.auth.oauth2.AuthorizationCodeInstalledApp.authorize(AuthorizationCodeInstalledApp.java:82)
        at fr.ffessm.doris.prefetch.ezpublish.DorisAPIConnexionHelper.authorizeViaWebPage(DorisAPIConnexionHelper.java:61)
        at fr.ffessm.doris.prefetch.PrefetchDorisWebSite.getInteractiveAccessToken(PrefetchDorisWebSite.java:260)
        at fr.ffessm.doris.prefetch.PrefetchDorisWebSite.doMain(PrefetchDorisWebSite.java:185)
        at fr.ffessm.doris.prefetch.PrefetchDorisWebSite.main(PrefetchDorisWebSite.java:123)

> Task :DorisAndroidPrefetch:BuildDorisDB FAILED

```

a current workaround is to use the code that is visible in the browser uri with curl:
(replace the XXX with the code, the app client_id and app client secret
```
curl -X POST \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "grant_type=authorization_code" \
  -d "code=XXX" \
  -d "redirect_uri=http://localhost:8087/Callback" \
  -d "client_id=XXX" \
  -d "client_secret=XXX" \
  https://doris.ffessm.fr/api/auth/oauth/token
```

I suspect an update on the server side that doesn't accept the request from our google-auth-client version ( that is quite old: 1.20)

**Comment by mikel879881** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.
