### ISSUE TITLE
[Crash]NullPointerException sur Fiche.getFicheFromHtml(Fiche.java:336) depuis VerifieMAJFiche_BgActivity

### ISSUE THREAD

**Issue by dvojtise** [doris-ffessm/doris-android#30]
In GitLab by @doris_bot on Apr 30, 2014, 14:45

__Imported issue:__ This issue was initially reported by _@dvojtise_ in https://gforge.inria.fr/tracker/?func=detail&aid=17353 (Additionnal comments haven't been imported and may still be there)

---

Remonté la première fois le 30/04/2014

USER_COMMENT=null

ANDROID_VERSION=4.4.2

APP_VERSION_NAME=2.1.0

BRAND=google

PHONE_MODEL=Nexus 5

CUSTOM_DATA=

STACK_TRACE=java.lang.RuntimeException: An error occured while executing doInBackground()

at android.os.AsyncTask$3.done(AsyncTask.java:300)

at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)

at java.util.concurrent.FutureTask.setException(FutureTask.java:222)

at java.util.concurrent.FutureTask.run(FutureTask.java:242)

at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

at java.lang.Thread.run(Thread.java:841)

Caused by: java.lang.NullPointerException

at fr.ffessm.doris.android.datamodel.Fiche.getFicheFromHtml(Fiche.java:336)

at fr.ffessm.doris.android.async.VerifieMAJFiche_BgActivity.doInBackground(VerifieMAJFiche_BgActivity.java:173)

at fr.ffessm.doris.android.async.VerifieMAJFiche_BgActivity.doInBackground(VerifieMAJFiche_BgActivity.java:74)

at android.os.AsyncTask$2.call(AsyncTask.java:288)

at java.util.concurrent.FutureTask.run(FutureTask.java:237)

... 4 more

java.lang.NullPointerException

at fr.ffessm.doris.android.datamodel.Fiche.getFicheFromHtml(Fiche.java:336)

at fr.ffessm.doris.android.async.VerifieMAJFiche_BgActivity.doInBackground(VerifieMAJFiche_BgActivity.java:173)

at fr.ffessm.doris.android.async.VerifieMAJFiche_BgActivity.doInBackground(VerifieMAJFiche_BgActivity.java:74)

at android.os.AsyncTask$2.call(AsyncTask.java:288)

at java.util.concurrent.FutureTask.run(FutureTask.java:237)

at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

at java.lang.Thread.run(Thread.java:841)

**Comment by dvojtise** [comment]
This feature is completely deprecated since we now use the API to get the data.

The old html scrapping code should be completely removed. (this is a legacy from the first versions based on the old web site )
Even if this implies that the user cannot update the data directly.  (May be we can think to another way to update data without updating the whole app but this should be another task.


Action:
- [ ] remove button allowing to update a `Fiche`
- [ ] remove code
- [ ] remove associated dependencies (jericho ...)
